mysqlHost: "mydatabase.example.com"
mysqlPort: 3306
mysqlUsername: "root"
mysqlPassword: "U3VwZXJTZWNyZXRQYXNzd29yZA==" #SuperSecretPassword
mysqlDatabaseName: "bank"

image:
  frontend: registry.humanitec.io/public/bank-demo-frontend:latest
  moneyapi: registry.humanitec.io/public/bank-demo-money-api:latest
  usersapi: registry.humanitec.io/public/bank-demo-users-api:latest
  pullPolicy: Always