apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneyapi-deployment
  labels:
    app: moneyapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moneyapi
  template:
    metadata:
      labels:
        app: moneyapi
    spec:
      containers:
      - name: moneyapi
        image: {{ .Values.image.api }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: user
        - name: DB_DATABASE
          value: application
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "50m"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: moneyapi-svc
spec:
  type: ClusterIP
  selector:
    app: moneyapi
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-moneyapi
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moneyapi-svc
            port:
              number: 80
  ingressClassName: nginx